apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cm9vdFBhc3N3b3Jk
# Example:
# password: {{ .Values.password | b64enc }}
